# Generated by Django 4.2.21 on 2025-10-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientNumber',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
