# Generated by Django 4.2.21 on 2025-10-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_patient_patientnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patientNumber',
            new_name='patient_number',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
