# Generated by Django 4.2.21 on 2025-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),

        ),
    ]
