# Generated by Django 4.2.21 on 2025-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_patient_age_alter_patient_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
