# Generated by Django 4.2.21 on 2025-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
