# Generated by Django 4.2.21 on 2025-10-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='current_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Checked In', 'Checked In'), ('Pre-Procedure', 'Pre-Procedure'), ('In-Progress', 'In-Progress'), ('Closing', 'Closing'), ('Recovery', 'Recovery'), ('Complete', 'Complete'), ('Dismissal', 'Dismissal')], default='Scheduled', max_length=50),
        ),
    ]
